[env:pico32]
platform = espressif32@6.12.0
board = pico32
framework = arduino

monitor_speed = 115200

board_build.partitions = partitions.csv

build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue